name = "NamedTrajectories"
uuid = "538bc3a1-5ab9-4fc3-b776-35ca1e893e08"
authors = ["Aaron Trowbridge <aaron.j.trowbridge@gmail.com> and contributors"]
version = "0.3.0"

[deps]
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
PlottingExt = ["Makie"]

[compat]
JLD2 = "0.5"
Makie = "0.22"
OrderedCollections = "1.7"
Reexport = "1.2"
TestItemRunner = "1.0"
TestItems = "1.0"
julia = "1.10, 1.11"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CairoMakie", "Test"]
